server:
    shutdown: graceful
    port: ${SERVER_LOCAL_PORT:8080}
spring:
    main:
        allow-bean-definition-overriding: true
    devtools:
        restart:
            enabled: false
    data:
        mongodb:
            auto-index-creation: true
            uuid-representation: standard
            field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
    redis:
        host: localhost
        port: 6379
    pid:
        file: ${instance.pid:8282282}

application:
    version: /v1
    prefix: /api
    exclude-prefix-path: springdoc

coroutine:
    io:
        pool:
            thread-name-prefix: ${balcony.front.api.coroutine.io.pool.nameprefix:cms-io}

management:
    endpoints:
        web:
            exposure:
                include: metrics, prometheus, health

logging:
    level:
        root: ${cms.app.api.logging.level.root:DEBUG}
        org.springframework.data.convert.CustomConversions: ERROR
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: ${cms.app.api.logging.level.mongo:DEBUG}
        io:
            spring:
                cloud: INFO

